version: "3.4"

volumes:
  db_data:
    driver: local

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gominohi
      - POSTGRES_PASSWORD=gominohi
