default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: gominohi_development
  username: gominohi
  password: gominohi

test:
  <<: *default
  database: gominohi_test
  username: gominohi
  password: gominohi

production:
  <<: *default
  database: gominohi_production
  username: gominohi
  password: <%= ENV['GOMINOHI_DATABASE_PASSWORD'] %>
